#!/usr/bin/env bash

ignore_files=".git|node_modules|_templates|customize|README.md"

for input_file in `tree -I "${ignore_files}" -Ffai --noreport`
do
  if [ ! -d "${input_file}" ]; then
    echo "Processing file: ${input_file}"
    gomplate \
         -f "${input_file}" \
         -o "${input_file}" \
         --left-delim "<<[" \
         --right-delim "]>>" \
         -c cus=./customize.json
  fi
done

# Rename module directory
./rename-module-dir

# Clean up / implode
rm README.md
rm rename-module-dir
mv README_TEMPLATE.md README.md
rm customize
